Repository video-dev/hls.js, pull requests merged in 2018-08, with the labels that each got.

#1841 Support universal builds ("SSR")
  scripts/travis.sh
  webpack.config.js
Labels: Ready-to-merge

#1840 Only compute PTS using timeoffset when the ID3 timestamp is NaN
  src/demux/aacdemuxer.js
Labels: Bug

#1854 Improve fragment searching via PDT
  src/controller/abr-controller.js
  src/controller/audio-stream-controller.js
  src/controller/buffer-controller.js
  src/controller/fragment-finders.js
  src/controller/fragment-tracker.js
  src/controller/level-helper.js
  src/controller/stream-controller.js
  src/demux/demuxer.js
  src/loader/fragment-loader.js
  src/loader/fragment.js
  src/loader/level.js
  src/loader/m3u8-parser.js
  src/loader/playlist-loader.js
  src/polyfills/number-isFinite.js
  src/utils/discontinuities.js
  src/utils/webvtt-parser.js
  tests/mocks/data.js
  tests/unit/controller/fragment-finders.js
  tests/unit/controller/stream-controller.js
  tests/unit/loader/fragment.js
  tests/unit/loader/level.js
  tests/unit/loader/playlist-loader.js
  tests/unit/utils/discontinuities.js
  webpack.config.js
Labels: Bug

#1810 Release with travis
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .travis.yml
  README.md
  demo/index.html
  dist/hls-demo.js
  dist/hls-demo.js.map
  dist/hls.js
  dist/hls.js.map
  dist/hls.light.js
  dist/hls.light.js.map
  dist/hls.light.min.js
  dist/hls.light.min.js.map
  dist/hls.min.js
  dist/hls.min.js.map
  docs/release-process.md
  package-lock.json
  package.json
  scripts/check-already-published.js
  scripts/set-canary-version.js
  scripts/set-package-version.js
  scripts/travis.sh
Labels: Ready-to-merge

#1853 fix initial audio track selection
  src/controller/audio-track-controller.js
  tests/unit/controller/audio-track-controller.js
Labels: Bug, Ready-to-merge

#1867 v0.11.0 regression fixes
  src/controller/audio-track-controller.js
  src/controller/level-controller.js
  src/demux/aacdemuxer.js
  src/demux/demuxer-inline.js
  src/loader/playlist-loader.js
Labels: Bug

#1866 Fix/worker performance now usage
  src/demux/demuxer-inline.js
  src/demux/demuxer-worker.js
Labels: Bug

#1800 Migration to Typescript compiler
  .babelrc
  .esdoc.json
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  scripts/foldersize.js
  scripts/lint.sh
  scripts/precommit.sh
  src/demux/demuxer-worker.js
  src/demux/demuxer.js
  src/hls.js
  src/loader/fragment.js
  src/loader/level-key.js
  src/loader/m3u8-parser.js
  src/polyfills/number-is-finite.js
  src/polyfills/number-isFinite.js
  tests/unit/controller/abr-controller.js
  tests/unit/controller/audio-track-controller.js
  tests/unit/controller/cap-level-controller.js
  tests/unit/controller/eme-controller.js
  tests/unit/controller/ewma-bandwidth-estimator.js
  tests/unit/controller/fragment-tracker.js
  tests/unit/controller/level-controller.js
  tests/unit/controller/subtitle-track-controller.js
  tests/unit/controller/timeline-controller.js
  tests/unit/demuxer/demuxer.js
  tests/unit/events.js
  tests/unit/loader/playlist-loader.js
  tests/unit/utils/attr-list.js
  tests/unit/utils/binary-search.js
  tests/unit/utils/buffer-helper.js
  tests/unit/utils/discontinuities.js
  tests/unit/utils/output-filter.js
  tsconfig.json
  webpack.config.js
Labels: Ready-to-merge

#1837 key-loader: set maxRetry to 0
  src/loader/key-loader.js
Labels: Ready-to-merge

#1869 fix(timeline-controller): reuse text tracks when not in same order
  src/controller/timeline-controller.js
  tests/unit/controller/timeline-controller.js
Labels: Ready-to-merge
