Repository video-dev/hls.js, pull requests merged in 2018-06, with the labels that each got.

#1767 Improve unit tests sourcemaps
  karma.conf.js
  tests/mocks/hls.mock.js
  tests/tests.webpack.js
  tests/unit/controller/eme-controller.js
Labels: Enhancement

#1630 Redundant streams fallback behavior for alternate renditions with multiple media groups
  demo/main.js
  src/controller/abr-controller.js
  src/controller/audio-stream-controller.js
  src/controller/audio-track-controller.js
  src/controller/level-controller.js
  src/controller/level-helper.js
  src/controller/stream-controller.js
  src/controller/subtitle-track-controller.js
  src/loader/m3u8-parser.js
  src/loader/playlist-loader.js
  src/task-loop.js
  src/utils/cea-608-parser.js
  src/utils/vttparser.js
  tests/functional/auto/testbench.js
  tests/unit/controller/audio-track-controller.js
Labels: Bug, Enhancement

#1786 Fix exceptions in IE
  .eslintrc.js
  src/crypt/decrypter.js
  src/demux/demuxer-inline.js
  src/demux/demuxer.js
  src/remux/mp4-generator.js
  src/utils/logger.js
  src/utils/make-array-from-array-like.js
Labels: Bug

#1795 Trigger BUFFER_NUDGE_ON_STALL before updating currentTime
  src/controller/stream-controller.js
Labels: Enhancement
