Repository video-dev/hls.js, pull requests merged in 2019-09, with the labels that each got.

#2352 Update functional tests to ES6.
  .travis.yml
  package-lock.json
  package.json
  tests/functional/auto/setup.js
  tests/functional/auto/testbench.js
Labels: CI

#2354 Fix for issue #2336: Remove misplaced timescale normalizing in delta computation
  src/remux/mp4-remuxer.js
  src/utils/timescale-conversion.ts
Labels: Bug

#2368 Fix bad conditional in key loader causing the wrong key to be loaded
  src/loader/key-loader.ts
Labels: Bug

#2379 Less verbose webpack output on CI, and attempt to build docs on travis
  package.json
  scripts/travis.sh
Labels: CI

#2380 Bugfix: Uncaught exception trying to flush back buffer when starting live stream
  src/controller/buffer-controller.ts
  tests/test-streams.js
Labels: Bug, Needs review
