Repository video-dev/hls.js, pull requests merged in 2019-04, with the labels that each got.

#2172 fix AudioStreamController when media is not attached
  src/controller/audio-stream-controller.js
Labels: Bug

#2220 create netlify sites under new team
  scripts/deploy-netlify.sh
Labels: CI

#2222 Update design.md
  docs/design.md
Labels: Docs

#2179 fix #2157 WEBVTT without X-TIMESTAMP-MAP
  src/utils/webvtt-parser.js
Labels: Needs review, Needs testing
