Repository video-dev/hls.js, pull requests merged in 2019-03, with the labels that each got.

#2148 Implement live VTT subtitle loading
  src/controller/audio-stream-controller.js
  src/controller/base-stream-controller.js
  src/controller/fragment-tracker.js
  src/controller/level-controller.js
  src/controller/level-helper.js
  src/controller/stream-controller.js
  src/controller/subtitle-stream-controller.js
  src/controller/subtitle-track-controller.js
  src/controller/timeline-controller.js
  src/hls.js
  tests/unit/controller/level-helper.js
  tests/unit/controller/subtitle-stream-controller.js
  tests/unit/controller/subtitle-track-controller.js
Labels: Bug, Ready-to-merge

#2166 Fix XSS on metrics page
  demo/metrics.html
Labels: Enhancement, Ready-to-merge

#2000 stream-controller: fix maxBufLen calculation
  src/controller/stream-controller.js
Labels: Documentation, Ready-to-merge

#2153 Fix Istanbul reporting
  karma.conf.js
  package-lock.json
  package.json
  tests/index.js
  tests/unit/utils/texttrack-utils.js
Labels: CI, Chore, Needs review

#1986 Adding the ability for CapLevelController to be enabled/disabled dynamically
  docs/API.md
  src/controller/cap-level-controller.js
  src/hls.js
  tests/unit/controller/cap-level-controller.js
Labels: Documentation, Enhancement, Feature proposal

#2169 only deploy hlsjs-latest when we are on newest master commit
  scripts/deploy-netlify.sh
Labels: CI

#2174 update webworkify-webpack to 2.1.5
  package-lock.json
  package.json
Labels: Bug, Tooling

#2196 Init segment should not be treated as start segment
  src/controller/audio-stream-controller.js
  src/controller/stream-controller.js
Labels: Bug

#2190 GH-2143: Fix flush buffer not accepting undefined types
  src/controller/buffer-controller.ts
  tests/unit/controller/buffer-controller.js
Labels: Bug

#2184 (misc) fixing incorrect default config values in API.md
  docs/API.md
Labels: Docs

#2199 (misc) Fix - Demo hls.js config persistence issue
  demo/main.js
Labels: Bug, Tooling
