Repository video-dev/hls.js, pull requests merged in 2019-11, with the labels that each got.

#2432 Cleaning Text Tracks cues on media detachment.
  src/controller/subtitle-track-controller.js
Labels: Bug

#2309 VTT cues are never cleaned up. Fix memory leak in live.
  src/controller/buffer-controller.ts
  src/controller/id3-track-controller.js
  src/events.js
  src/utils/texttrack-utils.ts
Labels: Enhancement

#2416 Fix demo errors
  demo/index.html
Labels: Bug

#2444 VWFlow to Clevercast
  README.md
Labels: Documentation
