Repository video-dev/hls.js, pull requests merged in 2019-02, with the labels that each got.

#2107 Apply TypeScript to Fragment & LevelKey
  src/controller/audio-stream-controller.js
  src/controller/stream-controller.js
  src/loader/fragment.js
  src/loader/fragment.ts
  src/loader/level-key.js
  src/loader/level-key.ts
  src/loader/m3u8-parser.js
  src/loader/playlist-loader.js
  tests/unit/loader/fragment.js
Labels: Ready-to-merge

#2119 Update webpack to use babel loader with support for TS.
  demo/main.js
  karma.conf.js
  package-lock.json
  package.json
  src/polyfills/number-isFinite.js
  src/polyfills/number.js
  tsconfig.json
  webpack.config.js
Labels: Ready-to-merge, Tooling

#2097 remove events/EventEmitter && move Observer to ts
  docs/design.md
  src/demux/demuxer-worker.js
  src/demux/demuxer.js
  src/observer.js
  src/observer.ts
  tests/unit/controller/eme-controller.js
  webpack.config.js
Labels: Enhancement, Needs review

#2116 Lint fixes
  src/config.js
  src/controller/abr-controller.js
  src/hls.js
  src/utils/logger.js
  tests/functional/auto/setup.js
  tests/functional/auto/testbench.js
Labels: Chore

#2128 (misc) Removing IE8-specific (dead) vtt/cue code
  src/utils/vttcue.js
Labels: Chore

#2129 Converting binary search helper to TS
  src/utils/binary-search.js
  src/utils/binary-search.ts
Labels: Enhancement, Needs review, Tooling

#2035 Reduce GC pressure from ID3._utf8ArrayToStr
  src/demux/id3.js
  tests/unit/demuxer/id3.js
Labels: Enhancement, Needs review

#2117 GH-2082: Replacing usage of Array.prototype.find/findIndex
  .eslintrc.js
  src/controller/level-controller.js
  src/controller/timeline-controller.js
Labels: Browser issue, Bug, Needs review

#2096 mp4-remuxer / remuxAudio() : recompute mdatSize / dont rely on audioTrack.len
  src/demux/adts.js
  src/demux/mpegaudio.js
  src/demux/tsdemuxer.js
  src/remux/mp4-remuxer.js
  tests/unit/demuxer/adts.js
Labels: Bug, Needs testing
