Repository video-dev/hls.js, pull requests merged in 2019-05, with the labels that each got.

#2229 Remove cue position alignment by adding 50 for Firefox
  src/utils/cues.js
Labels: Browser issue, Firefox, Needs review, Needs testing

#2126 Add SEI with resolution payloadType 5 based on H264 specification (Us…
  src/demux/tsdemuxer.js
Labels: Bug, Feature proposal

#1964 fix subtitle default track autoselect
  src/controller/subtitle-track-controller.js
Labels: Bug, Need tests, Waiting for author

#2254 New "They use hls.js in production!"
  README.md
Labels: Docs
