Repository video-dev/hls.js, pull requests merged in 2019-06, with the labels that each got.

#2248 Fix test coverage reporting
  karma.conf.js
  package-lock.json
  package.json
  tests/unit/demuxer/adts.js
Labels: Tooling

#2067 Fix alt-audio #2006
  src/controller/audio-stream-controller.js
  src/controller/base-stream-controller.js
  src/controller/stream-controller.js
Labels: Bug, Needs testing

#2269 docs: fix typo
  README.md
Labels: Docs

#2276 Add id prop back to track in buffer controler
  src/controller/buffer-controller.ts
  src/types/track.ts
Labels: Bug

#2284 support preprelease publishes from git tag
  docs/release-process.md
  scripts/get-version-tag.js
  scripts/set-package-version.js
  scripts/travis.sh
  scripts/version-parser.js
Labels: CI
