Repository video-dev/hls.js, pull requests merged in 2019-01, with the labels that each got.

#2075 Update light build targets to include Typescript extensions
  package-lock.json
  package.json
  webpack.config.js
Labels: Tooling

#2069 Docs: abrBandWidthFactor and abrBandWidthUpFactor
  docs/API.md
Labels: Docs

#2073 Buffer Controller TypeScript
  karma.conf.js
  package-lock.json
  package.json
  src/controller/buffer-controller.ts
  src/types/segment.ts
  src/types/track.ts
  src/utils/logger.js
  tests/unit/controller/buffer-controller.js
  tsconfig.json
Labels: Ready-to-merge, Tooling

#2086 Make bandwidth estimate public API
  docs/API.md
  src/hls.js
  tests/unit/controller/abr-controller.js
  tests/unit/hls.js
Labels: Documentation, Feature proposal, Ready-to-merge

#2052 Increase BufferHelper test coverage to 100%
  tests/unit/utils/buffer-helper.js
Labels: Ready-to-merge

#2053 Increase adts.js test coverage to 100%
  src/demux/adts.js
  tests/unit/demuxer/adts.js
Labels: Needs review

#2091 Choose bitrate in Bps
  docs/API.md
  src/utils/ewma-bandwidth-estimator.js
Labels: Docs, Enhancement, Needs review

#2076 EME Controller TypeScript
  .eslintrc.js
  src/controller/eme-controller.ts
Labels: Needs review, Ready-to-merge

#2101 configure netlify for PR's
  netlify.toml
  scripts/build-netlify.sh
  scripts/deploy-netlify.sh
  scripts/set-package-version.js
  scripts/travis.sh
Labels: Tooling

#2077 Adding config editor to demo page
  demo/index.html
  demo/main.js
  demo/style.css
Labels: Needs review, Tooling
