Repository video-dev/hls.js, pull requests merged in 2020-05, with the labels that each got.

#2505 Convert mpegaudio to TypeScript
  src/demux/mp3demuxer.ts
  src/demux/mpegaudio.ts
Labels: Waiting for author

#2719 update eventemitter3 to 4.0.3
  package-lock.json
  package.json
  src/observer.ts
Labels: dependencies

#2664 Close media key sessions and clear media keys when media detached
  src/controller/eme-controller.ts
  tests/unit/controller/eme-controller.js
Labels: Bug, Enhancement
