Repository video-dev/hls.js, pull requests merged in 2022-11, with the labels that each got.

#5007 Webpack 5 Upgrade
  .eslintrc.js
  .prettierignore
  karma.conf.js
  package-lock.json
  package.json
  src/demux/transmuxer-interface.ts
  src/demux/transmuxer-worker.ts
  src/demux/webworkify-webpack.js
  src/hls.ts
  src/utils/logger.ts
  webpack.config.js
Labels: CI

#4967 id3: add duration to metadata samples, mimic Safari behavior on unbounded cues
  api-extractor/report/hls.js.api.md
  src/controller/id3-track-controller.ts
  src/demux/base-audio-demuxer.ts
  src/demux/mp4demuxer.ts
  src/demux/tsdemuxer.ts
  src/types/demuxer.ts
Labels: metadata

#5009 Added deprecated event descriptions to API.md and MIGRATING.md
  MIGRATING.md
  docs/API.md
Labels: Documentation
