Repository video-dev/hls.js, pull requests merged in 2023-01, with the labels that each got.

#4842 Documentation - Add interface for AbrController
  docs/API.md
  src/controller/abr-controller.ts
  src/types/component-api.ts
Labels: ABR

#5159 Parse TARGETDURATION as a decimal-integer assigned a minimum value of 1
  src/loader/m3u8-parser.ts
  tests/unit/loader/playlist-loader.ts
Labels: Spec Compliance

#4825 Improve bandwidth estimation and adaptive switching
  api-extractor/report/hls.js.api.md
  demo/main.js
  src/controller/abr-controller.ts
  src/controller/audio-stream-controller.ts
  src/controller/base-stream-controller.ts
  src/controller/level-helper.ts
  src/controller/stream-controller.ts
  src/controller/subtitle-stream-controller.ts
  src/hls.ts
  src/utils/ewma-bandwidth-estimator.ts
  tests/unit/controller/stream-controller.ts
Labels: ABR

#5177 fix Netlify redirects
  package.json
  scripts/build-netlify.sh
Labels: CI

#5178 add a .node-version file and use in actions
  .github/workflows/build.yml
  .node-version
Labels: CI

#5180 switch to node 18, unpin `netlify-cli`, and workaround `npm ci` then being broken
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .node-version
  package-lock.json
  package.json
  scripts/get-package-version.js
  scripts/netlify.sh
  scripts/set-package-version.sh
  tests/functional/auto/setup.js
Labels: CI

#5179 switch back to official saucelabs action
  .github/workflows/build.yml
Labels: CI
